### ISSUE TITLE
컴파일 에러

### ISSUE THREAD

**Issue by jbari88** [es-meta/esmeta#218] opened 2024-05-10 03:48 UTC
기사보고 테스트해보고 싶어서 컴파일을 했는데요.

sbt assembly 명령어 실행 시, 아래와 같은 에러가 발생합니다.

[error] bad constant pool index: 0 at pos: 996
[error] -- [E008] Not Found Error: /{REDACTED}/esmeta/src/main/scala/esmeta/util/SystemUtils.scala:147:23
[error] 147 |    StandardCopyOption.REPLACE_EXISTING,
[error]     |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |value REPLACE_EXISTING is not a member of object java.nio.file.StandardCopyOption, but could be made available as an extension method.
[error]     |
[error]     |One of the following imports might make progress towards fixing the problem:
[error]     |
[error]     |  import akka.http.impl.util.JavaMapping.Implicits.convertToScala
[error]     |  import akka.http.javadsl.server.RoutingJavaMapping.Implicits.convertToScala
[error]     |
[error] three errors found
[error] (Compile / compileIncremental) Compilation failed

**Comment by hyp3rflow** [comment] 2024-05-10 04:47
안녕하세요. 사용 중이신 JDK 및 sbt 버전을 알려주실 수 있으실까요?

**Comment by jhnaldo** [comment] 2024-05-10 08:28
@jbari88 Thanks for your kind issue report. We just updated the version to [`v0.4.0`](https://github.com/es-meta/esmeta/releases/tag/v0.4.0). I believe that this version has resolved your problem. Can you re-install and check whether the problem is solved?

**Comment by jhnaldo** [comment] 2024-07-05 04:55
I will close this issue. If you still have the same problems, please reopen this issue!

**Closed as completed by jhnaldo** 2024-07-05 04:55 UTC
Labels: bug, framework
